### ISSUE TITLE
minimize button in black when using dark theme.

### ISSUE THREAD

**Issue by arun54321** [davidphilipbarr/adw-gtk-additional#1]
![r](https://user-images.githubusercontent.com/42943340/170806371-13c2c5ed-ce8b-44f3-97e9-f5df6c873896.png)

**Comment by davidphilipbarr** [comment]
ouch you are right, but they shouldn't have been there in the first place!  
They are the window icons from the hydrogen theme 
[https://github.com/tau-OS/tau-hydrogen](https://github.com/tau-OS/tau-hydrogen) which is very nice, especially the symbolic icons, the window icons recolour properly from their git.
